### ISSUE TITLE
Can't run the tests

### ISSUE THREAD

**Issue by salomari** [simonschwartz/cloudwatch-synthetics-boilerplate#3]
Hello,

I'm new to Node JS, when I run `npm test:example-test` or `node -e 'require(\"./tests/example-test\").handler()'` nothing happens.

`node -v`
`v12.16.1`

`npm -v`
`6.13.4`

I created a simple server.js and I can run it with node.

How do I run the tests please?

**Comment by salomari** [comment]
I was able to run the test by removing the single quotes:
`node -e require(\"./tests/example-test\").handler()`

But after the browser opens the url, I get the following error:
C:\Users\Sameer\Downloads\cloudwatch-synthetics-boilerplate-master\cloudwatch-synthetics-boilerplate-master>node -e require(\"./tests/example-test\").handler()
(node:8844) UnhandledPromiseRejectionWarning: Error: Evaluation failed: DOMException: Failed to execute 'querySelector' on 'Document': The provided selector is empty.
    at __puppeteer_evaluation_script__:1:33
    at ExecutionContext.evaluateHandle (C:\Users\Sameer\Downloads\cloudwatch-synthetics-boilerplate-master\cloudwatch-synthetics-boilerplate-master\node_modules\puppeteer\lib\ExecutionContext.js:121:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ElementHandle.$ (C:\Users\Sameer\Downloads\cloudwatch-synthetics-boilerplate-master\cloudwatch-synthetics-boilerplate-master\node_modules\puppeteer\lib\JSHandle.js:378:20)
    at async DOMWorld.$ (C:\Users\Sameer\Downloads\cloudwatch-synthetics-boilerplate-master\cloudwatch-synthetics-boilerplate-master\node_modules\puppeteer\lib\DOMWorld.js:114:19)
    at async DOMWorld.click (C:\Users\Sameer\Downloads\cloudwatch-synthetics-boilerplate-master\cloudwatch-synthetics-boilerplate-master\node_modules\puppeteer\lib\DOMWorld.js:358:20)
    at async C:\Users\Sameer\Downloads\cloudwatch-synthetics-boilerplate-master\cloudwatch-synthetics-boilerplate-master\tests\example-test.js:18:11
    at async Object.executeStep (C:\Users\Sameer\Downloads\cloudwatch-synthetics-boilerplate-master\cloudwatch-synthetics-boilerplate-master\syn-1.0\Synthetics\index.js:19:12)
    at async exampleTest (C:\Users\Sameer\Downloads\cloudwatch-synthetics-boilerplate-master\cloudwatch-synthetics-boilerplate-master\tests\example-test.js:15:5)
    at async Object.exports.handler (C:\Users\Sameer\Downloads\cloudwatch-synthetics-boilerplate-master\cloudwatch-synthetics-boilerplate-master\tests\example-test.js:29:12)
  -- ASYNC --
    at ExecutionContext.<anonymous> (C:\Users\Sameer\Downloads\cloudwatch-synthetics-boilerplate-master\cloudwatch-synthetics-boilerplate-master\node_modules\puppeteer\lib\helper.js:110:27)
    at ElementHandle.$ (C:\Users\Sameer\Downloads\cloudwatch-synthetics-boilerplate-master\cloudwatch-synthetics-boilerplate-master\node_modules\puppeteer\lib\JSHandle.js:378:50)
    at ElementHandle.<anonymous> (C:\Users\Sameer\Downloads\cloudwatch-synthetics-boilerplate-master\cloudwatch-synthetics-boilerplate-master\node_modules\puppeteer\lib\helper.js:111:23)
    at DOMWorld.$ (C:\Users\Sameer\Downloads\cloudwatch-synthetics-boilerplate-master\cloudwatch-synthetics-boilerplate-master\node_modules\puppeteer\lib\DOMWorld.js:114:34)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async DOMWorld.click (C:\Users\Sameer\Downloads\cloudwatch-synthetics-boilerplate-master\cloudwatch-synthetics-boilerplate-master\node_modules\puppeteer\lib\DOMWorld.js:358:20)
    at async C:\Users\Sameer\Downloads\cloudwatch-synthetics-boilerplate-master\cloudwatch-synthetics-boilerplate-master\tests\example-test.js:18:11
    at async Object.executeStep (C:\Users\Sameer\Downloads\cloudwatch-synthetics-boilerplate-master\cloudwatch-synthetics-boilerplate-master\syn-1.0\Synthetics\index.js:19:12)
    at async exampleTest (C:\Users\Sameer\Downloads\cloudwatch-synthetics-boilerplate-master\cloudwatch-synthetics-boilerplate-master\tests\example-test.js:15:5)
    at async Object.exports.handler (C:\Users\Sameer\Downloads\cloudwatch-synthetics-boilerplate-master\cloudwatch-synthetics-boilerplate-master\tests\example-test.js:29:12)
  -- ASYNC --
    at Frame.<anonymous> (C:\Users\Sameer\Downloads\cloudwatch-synthetics-boilerplate-master\cloudwatch-synthetics-boilerplate-master\node_modules\puppeteer\lib\helper.js:110:27)
    at Page.click (C:\Users\Sameer\Downloads\cloudwatch-synthetics-boilerplate-master\cloudwatch-synthetics-boilerplate-master\node_modules\puppeteer\lib\Page.js:1015:29)
    at C:\Users\Sameer\Downloads\cloudwatch-synthetics-boilerplate-master\cloudwatch-synthetics-boilerplate-master\tests\example-test.js:18:22
    at Object.executeStep (C:\Users\Sameer\Downloads\cloudwatch-synthetics-boilerplate-master\cloudwatch-synthetics-boilerplate-master\syn-1.0\Synthetics\index.js:19:18)
    at exampleTest (C:\Users\Sameer\Downloads\cloudwatch-synthetics-boilerplate-master\cloudwatch-synthetics-boilerplate-master\tests\example-test.js:15:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.exports.handler (C:\Users\Sameer\Downloads\cloudwatch-synthetics-boilerplate-master\cloudwatch-synthetics-boilerplate-master\tests\example-test.js:29:12)
(node:8844) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8844) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
